<?php

namespace SiteadminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteadminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteadminRepository extends EntityRepository
{
}
