siteadmin_index:
    path:     /
    defaults: { _controller: "SiteadminBundle:Siteadmin:index" }
    methods:  GET

siteadmin_show:
    path:     /{id}/show
    defaults: { _controller: "SiteadminBundle:Siteadmin:show" }
    methods:  GET

siteadmin_new:
    path:     /new
    defaults: { _controller: "SiteadminBundle:Siteadmin:new" }
    methods:  [GET, POST]

siteadmin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteadminBundle:Siteadmin:edit" }
    methods:  [GET, POST]

siteadmin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteadminBundle:Siteadmin:delete" }
    methods:  DELETE
